# Generated by Django 5.1 on 2024-08-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadalert',
            name='population_count',
            field=models.IntegerField(default=0),
        ),
    ]
